import Column from "../Shared/Components/Grid/Column";
import Grid from "../Shared/Components/Grid/Grid";

const PhrasesPage = () => {
  const data = [
    { id: 1, name: 'John', age: 23, country: 'Poland' },
    { id: 2, name: 'Alice', age: 31, country: 'France' },
    { id: 3, name: 'Michael', age: 45, country: 'USA' },
    { id: 4, name: 'Sophia', age: 28, country: 'Germany' },
    { id: 5, name: 'David', age: 35, country: 'Canada' },
    { id: 6, name: 'Emma', age: 27, country: 'UK' },
    { id: 7, name: 'Daniel', age: 29, country: 'Australia' },
    { id: 8, name: 'Maria', age: 40, country: 'Italy' },
    { id: 9, name: 'James', age: 33, country: 'Spain' },
    { id: 10, name: 'Isabella', age: 26, country: 'Mexico' },
    { id: 11, name: 'William', age: 30, country: 'Brazil' },
    { id: 12, name: 'Olivia', age: 32, country: 'Argentina' },
    { id: 13, name: 'Ethan', age: 36, country: 'South Africa' },
    { id: 14, name: 'Sophia', age: 25, country: 'Sweden' },
    { id: 15, name: 'Alexander', age: 39, country: 'Norway' },
    { id: 16, name: 'Ava', age: 34, country: 'Netherlands' },
    { id: 17, name: 'Mason', age: 41, country: 'Denmark' },
    { id: 18, name: 'Charlotte', age: 37, country: 'Switzerland' },
    { id: 19, name: 'Jacob', age: 38, country: 'Belgium' },
    { id: 20, name: 'Amelia', age: 42, country: 'Austria' },
    { id: 21, name: 'Liam', age: 24, country: 'Ireland' },
    { id: 22, name: 'Harper', age: 43, country: 'Portugal' },
    { id: 23, name: 'Benjamin', age: 44, country: 'Greece' },
    { id: 24, name: 'Evelyn', age: 46, country: 'Ukraine' },
    { id: 25, name: 'Michael', age: 47, country: 'India' },
    { id: 26, name: 'Elijah', age: 48, country: 'Japan' },
    { id: 27, name: 'Emily', age: 49, country: 'China' },
    { id: 28, name: 'Matthew', age: 50, country: 'South Korea' },
    { id: 29, name: 'Abigail', age: 51, country: 'Singapore' },
    { id: 30, name: 'Joshua', age: 52, country: 'Thailand' },
    { id: 31, name: 'Mia', age: 53, country: 'Philippines' },
    { id: 32, name: 'Liam', age: 54, country: 'Vietnam' },
    { id: 33, name: 'Mason', age: 55, country: 'Malaysia' },
    { id: 34, name: 'Sophia', age: 56, country: 'Indonesia' },
    { id: 35, name: 'Ethan', age: 57, country: 'New Zealand' },
    { id: 36, name: 'Olivia', age: 58, country: 'Saudi Arabia' },
    { id: 37, name: 'Daniel', age: 59, country: 'United Arab Emirates' },
    { id: 38, name: 'Emily', age: 60, country: 'Israel' },
    { id: 39, name: 'Alexander', age: 61, country: 'Egypt' },
    { id: 40, name: 'Isabella', age: 62, country: 'Turkey' },
    { id: 41, name: 'William', age: 63, country: 'Iran' },
    { id: 42, name: 'Sophia', age: 64, country: 'Iraq' },
    { id: 43, name: 'James', age: 65, country: 'Syria' },
    { id: 44, name: 'Ava', age: 66, country: 'Lebanon' },
    { id: 45, name: 'Jacob', age: 67, country: 'Jordan' },
    { id: 46, name: 'Ethan', age: 68, country: 'Kuwait' },
    { id: 47, name: 'Mia', age: 69, country: 'Qatar' },
    { id: 48, name: 'Michael', age: 70, country: 'Oman' },
    { id: 49, name: 'Daniel', age: 71, country: 'Yemen' },
    { id: 50, name: 'Olivia', age: 72, country: 'Bahrain' },
    { id: 51, name: 'Sophia', age: 73, country: 'Afghanistan' },
    { id: 52, name: 'Alexander', age: 74, country: 'Pakistan' },
    { id: 53, name: 'Emily', age: 75, country: 'Bangladesh' },
    { id: 54, name: 'Daniel', age: 76, country: 'Nepal' },
    { id: 55, name: 'Mason', age: 77, country: 'Sri Lanka' },
    { id: 56, name: 'Amelia', age: 78, country: 'Maldives' },
    { id: 57, name: 'James', age: 79, country: 'Bhutan' },
    { id: 58, name: 'Ethan', age: 80, country: 'Myanmar' },
    { id: 59, name: 'Sophia', age: 81, country: 'Cambodia' },
    { id: 60, name: 'Jacob', age: 82, country: 'Laos' },
    { id: 61, name: 'Evelyn', age: 83, country: 'Vietnam' },
    { id: 62, name: 'Elijah', age: 84, country: 'Indonesia' },
    { id: 63, name: 'Michael', age: 85, country: 'Philippines' },
    { id: 64, name: 'William', age: 86, country: 'Malaysia' },
    { id: 65, name: 'Mia', age: 87, country: 'Singapore' },
    { id: 66, name: 'Alexander', age: 88, country: 'Thailand' },
    { id: 67, name: 'Ava', age: 89, country: 'Vietnam' },
    { id: 68, name: 'Olivia', age: 90, country: 'South Korea' },
    { id: 69, name: 'Daniel', age: 91, country: 'Japan' },
    { id: 70, name: 'Sophia', age: 92, country: 'China' },
    { id: 71, name: 'Ethan', age: 93, country: 'India' },
    { id: 72, name: 'Mason', age: 94, country: 'Russia' },
    { id: 73, name: 'Amelia', age: 95, country: 'Germany' },
    { id: 74, name: 'Michael', age: 96, country: 'France' },
    { id: 75, name: 'Evelyn', age: 97, country: 'UK' },
    { id: 76, name: 'Olivia', age: 98, country: 'Australia' },
    { id: 77, name: 'Jacob', age: 99, country: 'Italy' },
    { id: 78, name: 'Elijah', age: 100, country: 'Spain' },
    { id: 79, name: 'Mia', age: 101, country: 'Mexico' },
    { id: 80, name: 'Alexander', age: 102, country: 'Brazil' },
    { id: 81, name: 'William', age: 103, country: 'Argentina' },
    { id: 82, name: 'Ava', age: 104, country: 'South Africa' },
    { id: 83, name: 'Olivia', age: 105, country: 'Sweden' },
    { id: 84, name: 'Ethan', age: 106, country: 'Norway' },
    { id: 85, name: 'Daniel', age: 107, country: 'Netherlands' },
    { id: 86, name: 'Sophia', age: 108, country: 'Denmark' },
    { id: 87, name: 'Mason', age: 109, country: 'Switzerland' },
    { id: 88, name: 'Olivia', age: 110, country: 'Belgium' },
    { id: 89, name: 'Alexander', age: 111, country: 'Austria' },
    { id: 90, name: 'Mia', age: 112, country: 'Ireland' },
    { id: 91, name: 'Elijah', age: 113, country: 'Portugal' },
    { id: 92, name: 'Olivia', age: 114, country: 'Greece' },
    { id: 93, name: 'Sophia', age: 115, country: 'Poland' },
    { id: 94, name: 'Alexander', age: 116, country: 'India' },
    { id: 95, name: 'William', age: 117, country: 'Japan' },
    { id: 96, name: 'Mia', age: 118, country: 'China' },
    { id: 97, name: 'Elijah', age: 119, country: 'South Korea' },
    { id: 98, name: 'Olivia', age: 120, country: 'Singapore' },
    { id: 99, name: 'Sophia', age: 121, country: 'Thailand' },
    { id: 100, name: 'Alexander', age: 122, country: 'Philippines' },
    { id: 101, name: 'William', age: 123, country: 'Vietnam' },
    { id: 102, name: 'Mia', age: 124, country: 'Malaysia' },
    { id: 103, name: 'Elijah', age: 125, country: 'Indonesia' },
    { id: 104, name: 'Olivia', age: 126, country: 'New Zealand' },
    { id: 105, name: 'Sophia', age: 127, country: 'Saudi Arabia' },
    { id: 106, name: 'Alexander', age: 128, country: 'United Arab Emirates' },
    { id: 107, name: 'William', age: 129, country: 'Israel' },
    { id: 108, name: 'Mia', age: 130, country: 'Egypt' },
    { id: 109, name: 'Elijah', age: 131, country: 'Turkey' },
    { id: 110, name: 'Olivia', age: 132, country: 'Iran' },
    { id: 111, name: 'Sophia', age: 133, country: 'Iraq' },
  ];
  return (
    <>
      {/* <p>Phrases page</p> */}
      <Grid dataSource={{ data: data }}>
        <Column field="id" title="ID"></Column>
        <Column field="name" title="Name"></Column>
        <Column field="age" title="Age"></Column>
        <Column field="country" title="Country"></Column>
      </Grid>
    </>
  );
}

export default PhrasesPage;
